/**
 * Generate TypeScript ABIs from Foundry's compiled artifacts.
 *
 * Hand-transcribed ABIs are a silent-failure surface: a wrong argument type produces a call the node
 * accepts and the contract misreads, or an encoding that reverts for reasons that look like a chain
 * problem. Generating them means the harness cannot drift from the contracts it talks to, and a signature
 * change in Solidity shows up as a TypeScript error rather than a runtime surprise.
 *
 *   node scripts/gen-abi.mjs
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { dirname, join } from 'node:path'

const CONTRACTS = ['Code', 'Saine', 'Governor', 'Escrow', 'Targets', 'DCode', 'Treasury', 'Receiver', 'Satellite', 'VintageVault', 'Oracle']
const OUT_DIR = new URL('../../contracts/out/', import.meta.url).pathname
const DEST = new URL('../src/chain/abi.ts', import.meta.url).pathname

const parts = [
  '// Generated by scripts/gen-abi.mjs from contracts/out. Do not edit by hand.',
  '// Regenerate after any change to a contract interface: `forge build && node scripts/gen-abi.mjs`.',
  '',
]

for (const name of CONTRACTS) {
  const path = join(OUT_DIR, `${name}.sol`, `${name}.json`)
  const artifact = JSON.parse(await readFile(path, 'utf8'))
  const abi = artifact.abi.filter((e) => e.type === 'function' || e.type === 'event' || e.type === 'error')
  parts.push(`export const ${name.toUpperCase()}_ABI = ${JSON.stringify(abi, null, 2)} as const`)
  parts.push('')
}

await mkdir(dirname(DEST), { recursive: true })
await writeFile(DEST, parts.join('\n'))
console.log(`wrote ${DEST} for ${CONTRACTS.length} contracts`)
