// SPDX-License-Identifier: AGPL-3.0-only
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";

/// @notice Cross-language parity for the SAINE attestation encoding.
///
/// @dev The agent harness signs in TypeScript; the registry verifies in Solidity. If the two disagree
///      by a single byte, every signature the board produces is rejected on chain, and the failure mode
///      is indistinguishable from ten agents going silent: the round lapses, and any slot that committed
///      first forfeits a quarter of its bond (§15) for a typo nobody can see.
///
///      So the encoding is pinned with literals generated by the TypeScript side
///      (`agent/test/fixtures/generate.ts`) and asserted here. Change either implementation and this
///      test fails, which is the only cheap way to catch a divergence that would otherwise surface as
///      an unexplained lapse on mainnet.
contract Eip712ParityTest is Test {
    bytes32 internal constant COMMIT_TYPEHASH =
        keccak256("Commit(uint256 roundId,uint8 slot,bytes32 commitment,bytes32 modelHash)");
    bytes32 internal constant REVEAL_TYPEHASH =
        keccak256("Reveal(uint256 roundId,uint8 slot,bool verdict,bytes32 reasonHash,bytes32 salt)");

    uint256 internal constant ROUND_ID = 7;
    uint8 internal constant SLOT = 3;

    function _commitment() internal pure returns (bytes32) {
        return keccak256("commitment-fixture");
    }

    function _modelHash() internal pure returns (bytes32) {
        return keccak256("model-fixture");
    }

    function _reasonHash() internal pure returns (bytes32) {
        return keccak256("reason-fixture");
    }

    function _salt() internal pure returns (bytes32) {
        return keccak256("salt-fixture");
    }

    function test_fixtureInputsAgree() public pure {
        assertEq(_commitment(), 0x144af20e1e5afce296b230f43aef17001b7e80327d2c4251db619058e84eda4b);
        assertEq(_modelHash(), 0xd89ae98c5747802d5b5ff1316fe8447eabe18b1ab0f35b84f08e073cef6fa4c0);
        assertEq(_reasonHash(), 0x9d6270abe3bcf14322b34e5d3ae83885193b14ff85fa5eb0a07ffb38c58e529f);
        assertEq(_salt(), 0x96633a17fa71afc4594351b8597bebbf7a5c1601047343ab4322035ca67c8599);
    }

    function test_commitStructHashMatchesTypeScript() public pure {
        bytes32 structHash = keccak256(abi.encode(COMMIT_TYPEHASH, ROUND_ID, SLOT, _commitment(), _modelHash()));
        assertEq(structHash, 0xe5bf37b7e39a0480587004d4dd777be5189739e82759e92ec2ff2ff97e1064b5);
    }

    function test_revealStructHashMatchesTypeScript() public pure {
        bytes32 structHash = keccak256(abi.encode(REVEAL_TYPEHASH, ROUND_ID, SLOT, true, _reasonHash(), _salt()));
        assertEq(structHash, 0x8ed18155a99e9f9145029ca40f1c2f9684390fa89b213f3c91226d37ef91da2c);
    }

    /// @dev The commitment itself, which the contract recomputes on reveal and compares. A mismatch
    ///      here reverts with `CommitmentMismatch` and the slot cannot reveal at all.
    function test_commitmentConstructionMatchesTypeScript() public pure {
        bytes32 commitment = keccak256(abi.encode(true, _reasonHash(), _salt()));
        assertEq(commitment, 0xb45c30cdf1a2cad0a8f3f1c2beb63a2cd53b19da2c8c9f8bb29228ee790f8ed2);
    }
}
